package rules;
import com.jim.learn.serviceprovider.po.User

rule "salience2"
salience 2
    when
        eval(true)
    then
        System.err.println("salience2");
end

rule "salience1"
salience 1
    when
        eval(true)
    then
        System.err.println("salience1");
end

rule "dateEffective"
date-effective "2021-01-14"
    when
    then
        System.err.println("2018-11-24被执行");
end

rule "dateEffectiveTomorrow"
date-expires "2018-11-25"
    when
    then
        System.err.println("2018-11-25被执行");
end