package rules;
import com.jim.learn.serviceprovider.po.User

rule "user"
    when
      $u:User(name=="张三",age==18)
    then
        $u.setName("李四");
        System.err.println("hello,word："+$u.getName());
end

rule "contains"
    when
     $s:String()
     $user:User(name contains $s)
    then
        System.out.println("用户"+$s+"存在");
end

rule "numberOf"
    when
     $list:List()
     $user:User(name memberOf $list)
    then
        System.out.println("用户"+$user.getName()+"存在");
end

rule "matches"
    when
     $u:User(name matches "张.*")
    then
        System.err.println("用户"+$u.getName()+"存在");
    end